### ISSUE TITLE
 Unresolved attribute reference `self.hosts`

### ISSUE THREAD

**Issue by danielniccoli** [django/asgi_ipc#11]
See https://github.com/django/asgi_ipc/blob/b6750c51ab7e409450e52735454f38333ef06e2b/asgi_ipc.py#L168

I added a `# TODO` comment in my latest pull request.
https://github.com/django/asgi_ipc/pull/10/commits/980ccabf192c3fada294a5b1a32a4908887c058d#diff-64b224d30f0fb99ddead52f77c969d28R169

**Comment by andrewgodwin** [comment]
Yes, this is left over code from when it was copied from the Redis backend as a template I suspect. It should be replaced to show prefix instead.
