### ISSUE TITLE
MemoryDatastructure and double acquisition of semaphores

### ISSUE THREAD

**Issue by dilyanpalauzov** [django/asgi_ipc#16]
Hello,

```asgi_ipc.py:MemoryDatastructure._get_value()``` and ```MemoryDatastructure._set_value()``` acquire a semaphore, read/modify the shared memory and eventually release the semaphore.

The methods ```MemoryDatastructure.__setitem__```, ```MemoryDatastructure __delitem__``` and ```MemoryDict.discard``` call first ```_get_value()``` and then ```_set_value```.  This means, that they acquire the semaphore, read the data, release the semaphore, modify the data, acquire the semaphore again, write the new data, and release the semaphore.

Doesn't this cause race conditions?

Wouldn't asgi_ipc get faster, if during ```MemoryDatastructre.__setitem__``` the semaphore is acquired and released only once?

**Comment by andrewgodwin** [comment]
Yes, it likely does make it slower, but the performance of the IPC backend is very slow even when that's taken into account. I'd take a PR to fix it, but at this point I'm considering switching it to use SQLite on disk with locking instead.
