### ISSUE TITLE
Outdate asgiref

### ISSUE THREAD

**Issue by BryanHurst** [django/asgi_ipc#36]
It looks like this package is currently incompatible with the latest Django Channels as Channels requires asgiref 2.3.x and asgi_ipc requires asgiref 1.1.x.

Is there a real incompatibility here, or is it safe to bump the required asgiref version for this package?

**Comment by andrewgodwin** [comment]
There is real incompatibility. This package is for Channels 1 only, and does not work on Channels 2.
