### ISSUE TITLE
shared memory segment and semaphore names suffixes are too large for OS X

### ISSUE THREAD

**Issue by stratoukos** [django/asgi_ipc#4]
Asgi_ipc uses `"/%s-channel-dict"` for the shared memory segment name and `"/%s-channel-dict-semaphore"` (where %s is the configured prefix).

Mac OS X's IPC name sizes cannot be more than 30 bytes ([source](1), second list item). This means that the maximum usable prefix on OS X is 6 characters, which is pretty small.

One solution would be to change the suffixes to something smaller (like "-chan" and "-chan-sem"). I can provide a PR if this solution is ok.

Thanks.

**Comment by andrewgodwin** [comment]
Yes, that fix sounds good to me, and we should stick a nice validation check on the name length too.

**Comment by stratoukos** [comment]
I'm not sure how would we validate that, since every system has different max sizes. After a bit of testing I got these max values:
- linux semaphore name: 251
- linux shared memory key: 255
- freebsd semaphore name: 252
- freebsd shared memory key: 1023
- os x semaphore name: 30
- os x shared memory key: 30

We could maintain a list of hardcoded values, but this sounds like a bad idea. 

Posix-ipc already raises `ValueError: The name is too long` for these cases, so the error is not that bad.

**Comment by andrewgodwin** [comment]
Ah, if the error is that clear then I think it's fine.
